android.useAndroidX=true
android.nonTransitiveRClass=true
org.gradle.jvmargs=-Xmx3072m

# 如需通过代理下载依赖，取消下面注释并修改为你的代理地址
# systemProp.http.proxyHost=127.0.0.1
# systemProp.http.proxyPort=18080
# systemProp.https.proxyHost=127.0.0.1
# systemProp.https.proxyPort=18080
# systemProp.http.nonProxyHosts=localhost|127.0.0.1
